"use client";
import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Github, Search } from "lucide-react";
import type { Project } from "@/lib/content";

export default function ProjectGrid({ projects }: { projects: Project[] }) {
  const [query,setQuery]=useState(""); const [filter,setFilter]=useState("All"); const categories=["All",...Array.from(new Set(projects.map(p=>p.category)))];
  const visible=useMemo(()=>projects.filter(p=>(filter==='All'||p.category===filter)&&(p.title.toLowerCase().includes(query.toLowerCase())||p.description.toLowerCase().includes(query.toLowerCase()))),[projects,filter,query]);
  return <div className="space-y-8"><div className="flex flex-col gap-3 rounded-2xl border border-white/8 bg-white/[.02] p-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{categories.map(c=><button key={c} onClick={()=>setFilter(c)} className={`rounded-full border px-4 py-2 text-xs transition ${filter===c?'border-cyan/40 bg-cyan/10 text-cyan':'border-white/10 text-white/50 hover:border-white/20 hover:text-white'}`}>{c}</button>)}</div><label className="relative block min-w-0 lg:w-64"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-white/30"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects" className="w-full rounded-xl border border-white/10 bg-black/20 py-2.5 pl-9 pr-4 text-sm outline-none placeholder:text-white/25 focus:border-cyan/30"/></label></div>
    <motion.div layout className="grid gap-5 lg:grid-cols-2">{visible.map((p,i)=><motion.article layout key={p.slug} initial={{ opacity:0,y:24 }} whileInView={{opacity:1,y:0}} viewport={{ once:true, amount:.25 }} transition={{ delay:i*.04 }} className="group relative overflow-hidden rounded-[1.8rem] border border-white/10 bg-white/[.025] p-6 transition duration-500 hover:-translate-y-1 hover:border-white/20"><div className={`pointer-events-none absolute -right-20 -top-20 h-60 w-60 rounded-full blur-3xl ${p.accent==='cyan'?'bg-cyan/10':p.accent==='violet'?'bg-violet/10':'bg-lime/10'}`}/><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.28em] text-white/35">{p.category} · {p.year}</div><h3 className="mt-4 font-display text-3xl tracking-[-.03em]">{p.title}</h3></div><div className="rounded-full border border-white/10 px-3 py-1 text-[10px] text-white/40">0{i+1}</div></div><div className="my-8 aspect-[1.8] overflow-hidden rounded-[1.4rem] border border-white/8 bg-[#05080f]"><div className={`h-full w-full ${p.accent==='cyan'?'bg-[radial-gradient(circle_at_30%_25%,rgba(92,225,255,.22),transparent_28%),linear-gradient(135deg,#08121b,#07030f)]':p.accent==='violet'?'bg-[radial-gradient(circle_at_65%_25%,rgba(151,117,255,.23),transparent_28%),linear-gradient(135deg,#0d0817,#05060d)]':'bg-[radial-gradient(circle_at_45%_60%,rgba(202,255,107,.18),transparent_28%),linear-gradient(135deg,#0a1009,#05060d)]'}`}><div className="h-full w-full bg-[linear-gradient(rgba(255,255,255,.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.03)_1px,transparent_1px)] [background-size:40px_40px] opacity-70"/></div></div><p className="max-w-xl text-sm leading-6 text-white/52">{p.description}</p><div className="mt-5 flex flex-wrap gap-2">{p.stack.map(s=><span key={s} className="rounded-full border border-white/8 bg-white/[.03] px-2.5 py-1 text-[10px] text-white/45">{s}</span>)}</div><div className="mt-7 flex gap-3"><a href={p.liveUrl} className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2.5 text-xs font-semibold text-black transition hover:bg-cyan">Live preview <ArrowUpRight className="h-3.5 w-3.5"/></a><a href={p.githubUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2.5 text-xs text-white/65 hover:border-white/20 hover:text-white"><Github className="h-3.5 w-3.5"/> GitHub</a></div></motion.article>)}</motion.div>
    {!visible.length && <div className="rounded-[1.8rem] border border-dashed border-white/10 p-12 text-center text-white/40">No projects match this search.</div>}
  </div>;
}
